version: '3.9'

services:
  budget_buddy-db:
    image: postgres:15
    container_name: budget_buddy-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: budget_buddy
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: budget_buddy_db
    volumes:
      - budget_buddy_pgdata:/var/lib/postgresql/data
    networks:
      - budget_buddy-net

networks:
  budget_buddy-net:


volumes:
  budget_buddy_pgdata:
