version: '3.9'

services:
  template-db:
    image: postgres:15
    container_name: template-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: template
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: template_db
    volumes:
      - template_pgdata:/var/lib/postgresql/data
    networks:
      - template-net

networks:
  template-net:


volumes:
  template_pgdata:
